### ISSUE TITLE
Toolbar being shown instead of Action Bar

### ISSUE THREAD

**Issue by singh-karan-7** [shiburagi/whatsapp-searchbar#1]
I saw your example and tried to implement that but my app is showing Toolbar with 0 buttons(as there are no buttons in Toolbar itself) but it should show Action Bar initially with search action and other buttons. Do you know what might the problem be?

**Comment by shiburagi** [comment]
can you give me activity and xml code?

**Comment by singh-karan-7** [comment]
I have done it now. Don't know how, but I think putting Toolbar's definition below to that appBar and SearchBar and it's working now. Thanks for your time.

**Comment by shiburagi** [comment]
Okayy

**Comment by shiburagi** [comment]
Okayy
